name: my first workflow

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: List Repo files
              run: ls -ltra
           
            - name: Excute shell script
              run: |
 
 
                chmod +x asci-script.sh
                ./asci-script.sh   
 

          