name: cowsay-multi-job

on: push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install cowsay
        run: sudo apt-get install -y cowsay

  generate:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Create dragon message
        run: echo 'cowsay -f dragon "RAA! I am a dragon."' > dragon.sh

      - name: Make it executable
        run: chmod +x dragon.sh

      - name: Upload dragon.sh
        uses: actions/upload-artifact@v4
        with:
          name: dragon-script
          path: dragon.sh

  execute:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Download dragon.sh
        uses: actions/download-artifact@v4
        with:
          name: dragon-script

      - name: Install cowsay
        run: sudo apt-get install -y cowsay

      - name: Run the dragon message
        run: ./dragon.sh

  deploy:
    runs-on: ubuntu-latest
    needs: execute
    steps:
      - name: Final Deployment Step
        run: echo "🎉 Deployment done! All jobs completed successfully."
