name: cowsay-multi-job

on: push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install cowsay
        run: sudo apt-get install -y cowsay

  generate:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Create dragon.sh script
        run: echo 'cowsay -f dragon "RAA! I am a dragon."' > dragon.sh

      - name: Make script executable
        run: chmod +x dragon.sh

      - name: Upload dragon.sh as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-script
          path: dragon.sh

  execute:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Download dragon.sh from artifacts
        uses: actions/download-artifact@v4
        with:
          name: dragon-script

      - name: Make script executable again
        run: chmod +x dragon.sh

      - name: Install cowsay
        run: sudo apt-get install -y cowsay

      - name: Run the dragon message
        run: ./dragon.sh

  deploy:
    runs-on: ubuntu-latest
    needs: execute
    steps:
      - name: Deployment Step
        run: echo "🚀 Deployment Successful! All steps completed."